//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ligg.Winform.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ligg.Winform.Resources.ValidationRes", typeof(ValidationRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Can&apos;t Be Earlier Than &apos;{0}&apos;.
        /// </summary>
        public static string CanNotBeEarlierThan {
            get {
                return ResourceManager.GetString("CanNotBeEarlierThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Can&apos;t Be Future Time.
        /// </summary>
        public static string CanNotBeFutureTime {
            get {
                return ResourceManager.GetString("CanNotBeFutureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Can&apos;t Be Later Than &apos;{0}&apos;.
        /// </summary>
        public static string CanNotBeLaterThan {
            get {
                return ResourceManager.GetString("CanNotBeLaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Can&apos;t Be A Null Value.
        /// </summary>
        public static string CannotBeNull {
            get {
                return ResourceManager.GetString("CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Can&apos;t Be Past Time.
        /// </summary>
        public static string CanNotBePastTime {
            get {
                return ResourceManager.GetString("CanNotBePastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can&apos;t be zero.
        /// </summary>
        public static string CannotBeZero {
            get {
                return ResourceManager.GetString("CannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Format is incorrect.
        /// </summary>
        public static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name format isincorrect! File Name can only be composited by  alpha-numeric characters and - _..
        /// </summary>
        public static string FileNameFormat {
            get {
                return ResourceManager.GetString("FileNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name Must Contains Suffix Seperator ..
        /// </summary>
        public static string FileNameMustContainsSuffixSeperator {
            get {
                return ResourceManager.GetString("FileNameMustContainsSuffixSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input should be an integer.
        /// </summary>
        public static string IntegerInput {
            get {
                return ResourceManager.GetString("IntegerInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Is Mandatory.
        /// </summary>
        public static string MandatoryField {
            get {
                return ResourceManager.GetString("MandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input value should be between {0} to {1}.
        /// </summary>
        public static string NumberRange {
            get {
                return ResourceManager.GetString("NumberRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input should be numeral.
        /// </summary>
        public static string NumeraInput {
            get {
                return ResourceManager.GetString("NumeraInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is inconsistent.
        /// </summary>
        public static string PasswordConsistentence {
            get {
                return ResourceManager.GetString("PasswordConsistentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Format Is Incorrect! Password must be composited by following types: alpha, numeric characters and special characters（ !,@,#,$,%,* ,etc）, and can&apos;t be less than 7 chars.
        /// </summary>
        public static string PasswordFormat {
            get {
                return ResourceManager.GetString("PasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Format Is Incorrect! Password must be composited by  2 of following types: alpha, numeric characters and special characters（ !,@,#,$,%,* ,etc）, and can&apos;t be less than 7 chars.
        /// </summary>
        public static string PasswordFormat1 {
            get {
                return ResourceManager.GetString("PasswordFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Should Be Between  &apos;{0}&apos;  And &apos;{1}&apos;.
        /// </summary>
        public static string ShouldBeBetween {
            get {
                return ResourceManager.GetString("ShouldBeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alpha-numeric characters and Specific Character are allowed.
        /// </summary>
        public static string StringForAlphaAndNumAndSpecificChar {
            get {
                return ResourceManager.GetString("StringForAlphaAndNumAndSpecificChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alpha or numeric characters are allowed.
        /// </summary>
        public static string StringForAlphaOrNum {
            get {
                return ResourceManager.GetString("StringForAlphaOrNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alpha-numeric characters, . or @ are allowed.
        /// </summary>
        public static string StringForAlphaOrNumAndDotOrAt {
            get {
                return ResourceManager.GetString("StringForAlphaOrNumAndDotOrAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input chars should between {0}-{1}.
        /// </summary>
        public static string StringLengthRange {
            get {
                return ResourceManager.GetString("StringLengthRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string can&apos;t exceed {0} chars.
        /// </summary>
        public static string StringMaxLength {
            get {
                return ResourceManager.GetString("StringMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string can&apos;t be less than {0} chars.
        /// </summary>
        public static string StringMinLength {
            get {
                return ResourceManager.GetString("StringMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Format is incorrect.
        /// </summary>
        public static string WebUrlFormat {
            get {
                return ResourceManager.GetString("WebUrlFormat", resourceCulture);
            }
        }
    }
}
